name: dart_earcut
description: Performant triangulation algorithm based on https://github.com/mapbox/earcut
version: 1.2.0
repository: https://github.com/JaffaKetchup/dart_earcut

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.14
